# Generated by Django 3.0.3 on 2020-04-22 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_ingredient_pantry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_by_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pantry',
        ),
    ]
