# Generated by Django 3.0.3 on 2020-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20200426_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(default='google.com', max_length=255),
        ),
    ]
