# Generated by Django 3.0.3 on 2020-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_recipe_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='missing',
            field=models.CharField(max_length=2500),
        ),
    ]
