# Generated by Django 3.0.3 on 2020-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20200427_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='recipes',
            field=models.ManyToManyField(related_name='report_by_recipe', to='planner.Recipe'),
        ),
    ]
